// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SessionType is an enumeration to indicate the type of the session
// between 2 Node s.
type SessionType int32

const (
	SessionType_SINGLE_CALL SessionType = 0
	SessionType_MULTI_CALL  SessionType = 1
)

var SessionType_name = map[int32]string{
	0: "SINGLE_CALL",
	1: "MULTI_CALL",
}

var SessionType_value = map[string]int32{
	"SINGLE_CALL": 0,
	"MULTI_CALL":  1,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

// Node represents a unique endpoint (host + port) on the network.
//
// A single host can have multiple nodes running; seemingly within
// the same process. e.g. client and server of a p2p network.
type Node struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ipv4                 string   `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Node) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// Credentials will usually be a combination of username and a
// secret. It's upto the implementation to use plain text passwords
// or hashes as secrets.
type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

// Timeout defines the time in millis for a session. It can be sent
// as an argument to request a token after successfull authentication,
// or alongwith a Token to indicate the type of session and timeout
// associated with the Token.
type Timeout struct {
	SessionType          SessionType `protobuf:"varint,1,opt,name=session_type,json=sessionType,proto3,enum=proto.SessionType" json:"session_type,omitempty"`
	TimeInMillis         uint64      `protobuf:"varint,2,opt,name=time_in_millis,json=timeInMillis,proto3" json:"time_in_millis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Timeout) Reset()         { *m = Timeout{} }
func (m *Timeout) String() string { return proto.CompactTextString(m) }
func (*Timeout) ProtoMessage()    {}
func (*Timeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Timeout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timeout.Unmarshal(m, b)
}
func (m *Timeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timeout.Marshal(b, m, deterministic)
}
func (m *Timeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timeout.Merge(m, src)
}
func (m *Timeout) XXX_Size() int {
	return xxx_messageInfo_Timeout.Size(m)
}
func (m *Timeout) XXX_DiscardUnknown() {
	xxx_messageInfo_Timeout.DiscardUnknown(m)
}

var xxx_messageInfo_Timeout proto.InternalMessageInfo

func (m *Timeout) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SINGLE_CALL
}

func (m *Timeout) GetTimeInMillis() uint64 {
	if m != nil {
		return m.TimeInMillis
	}
	return 0
}

// Login message with be sent by one node to another, or by a client to
// a server. Upon login, if successfully authenticated, the client/ node
// will receive a token which it will then have to share with the server/
// other-node every time it sends/ receives messages.
type Login struct {
	Node                 *Node        `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Timeout              *Timeout     `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Login) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *Login) GetTimeout() *Timeout {
	if m != nil {
		return m.Timeout
	}
	return nil
}

// A Token is created everytime a Node is successfully authenticated. It contains
// a token value.
//
// The type of session affiliated with a Token is available as a Timeout type
// member in a token.
type Token struct {
	TokenVal             string   `protobuf:"bytes,1,opt,name=token_val,json=tokenVal,proto3" json:"token_val,omitempty"`
	SessionTimeout       *Timeout `protobuf:"bytes,2,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetTokenVal() string {
	if m != nil {
		return m.TokenVal
	}
	return ""
}

func (m *Token) GetSessionTimeout() *Timeout {
	if m != nil {
		return m.SessionTimeout
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.SessionType", SessionType_name, SessionType_value)
	proto.RegisterType((*Node)(nil), "proto.Node")
	proto.RegisterType((*Credentials)(nil), "proto.Credentials")
	proto.RegisterType((*Timeout)(nil), "proto.Timeout")
	proto.RegisterType((*Login)(nil), "proto.Login")
	proto.RegisterType((*Token)(nil), "proto.Token")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x0b, 0xd3, 0x30,
	0x18, 0xc6, 0x6d, 0xed, 0x36, 0xfb, 0x66, 0x76, 0xf2, 0x1e, 0x64, 0x28, 0x68, 0x29, 0x1e, 0x8a,
	0x87, 0x0e, 0xe6, 0xc4, 0x9b, 0x30, 0x87, 0xc8, 0xa0, 0xdb, 0x21, 0xab, 0x1e, 0x04, 0x29, 0x5d,
	0x1b, 0x67, 0x58, 0x9b, 0x94, 0x26, 0x1b, 0xec, 0x1b, 0xf8, 0xb1, 0xa5, 0x69, 0xf7, 0xe7, 0xe0,
	0x29, 0xef, 0xf3, 0xbc, 0xed, 0x2f, 0x79, 0x1e, 0x70, 0x2b, 0x75, 0x88, 0xea, 0x46, 0x6a, 0x89,
	0x03, 0x73, 0x04, 0x9f, 0xc1, 0xd9, 0xca, 0x82, 0xa1, 0x07, 0x36, 0x2f, 0xa6, 0x96, 0x6f, 0x85,
	0x0e, 0xb5, 0x79, 0x81, 0x08, 0x0e, 0xaf, 0xcf, 0x8b, 0xa9, 0xed, 0x5b, 0xa1, 0x4b, 0xcd, 0xdc,
	0x7a, 0xb5, 0x6c, 0xf4, 0xf4, 0xa9, 0x6f, 0x85, 0xcf, 0xa9, 0x99, 0x83, 0x25, 0x90, 0x55, 0xc3,
	0x0a, 0x26, 0x34, 0xcf, 0x4a, 0x85, 0xaf, 0xe0, 0xd9, 0x49, 0xb1, 0x46, 0x64, 0x15, 0x33, 0x30,
	0x97, 0xde, 0x34, 0xbe, 0x84, 0xa1, 0x62, 0x79, 0xc3, 0x74, 0x0f, 0xed, 0x55, 0xf0, 0x1b, 0x46,
	0x09, 0xaf, 0x98, 0x3c, 0x69, 0xfc, 0x08, 0x63, 0xc5, 0x94, 0xe2, 0x52, 0xa4, 0xfa, 0x52, 0x77,
	0x08, 0x6f, 0x8e, 0xdd, 0x93, 0xa3, 0x5d, 0xb7, 0x4a, 0x2e, 0x35, 0xa3, 0x44, 0xdd, 0x05, 0xbe,
	0x03, 0x4f, 0xf3, 0x8a, 0xa5, 0x5c, 0xa4, 0x15, 0x2f, 0x4b, 0xae, 0xcc, 0x0d, 0x0e, 0x1d, 0xb7,
	0xee, 0x5a, 0x6c, 0x8c, 0x17, 0xfc, 0xb5, 0x60, 0x10, 0xcb, 0x03, 0x17, 0xf8, 0x16, 0x1c, 0x21,
	0x8b, 0x0e, 0x4f, 0xe6, 0xa4, 0xc7, 0xb7, 0x3d, 0x50, 0xb3, 0xc0, 0x05, 0x90, 0xfc, 0x9e, 0xca,
	0xd0, 0xc8, 0xed, 0x19, 0x0f, 0x79, 0xe9, 0xe3, 0x67, 0x18, 0xc2, 0x48, 0x77, 0x41, 0x4c, 0x45,
	0x64, 0xee, 0xf5, 0x7f, 0xf4, 0xf1, 0xe8, 0x75, 0x1d, 0xfc, 0x82, 0x41, 0x22, 0x8f, 0x4c, 0xe0,
	0x6b, 0x70, 0x75, 0x3b, 0xa4, 0xe7, 0xac, 0xbc, 0x16, 0x66, 0x8c, 0x1f, 0x59, 0x89, 0x9f, 0x60,
	0x72, 0x6b, 0xa3, 0xe7, 0xda, 0xff, 0xe5, 0x7a, 0xd7, 0x32, 0x3a, 0xfd, 0x3e, 0x02, 0xf2, 0xd0,
	0x15, 0x4e, 0x80, 0xec, 0xd6, 0xdb, 0x6f, 0xf1, 0xd7, 0x74, 0xb5, 0x8c, 0xe3, 0x17, 0x4f, 0xd0,
	0x03, 0xd8, 0x7c, 0x8f, 0x93, 0x75, 0xa7, 0xad, 0x2f, 0xfe, 0xcf, 0x37, 0x07, 0xae, 0xff, 0x9c,
	0xf6, 0x51, 0x2e, 0xab, 0x99, 0xac, 0x99, 0x50, 0xb5, 0xcc, 0x8f, 0x33, 0xc1, 0xf4, 0xcc, 0xdc,
	0xb4, 0x1f, 0x9a, 0xe3, 0xc3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x9c, 0x35, 0xcb, 0x41,
	0x02, 0x00, 0x00,
}
